[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jayyyu1w", email = "jayyu1w@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "langchain>=1.4.3",
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.6.6",
    "langchain-ollama>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.12",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]

[tool.uv]
package = false